### ISSUE TITLE
脚本文件里好像有错，可以确认下吗？

### ISSUE THREAD

**Issue by lixi92** [gaobb/DCFS#6]
----------------------------- Model Preparation --------------------------------- 
python3 tools/model_surgery.py --dataset voc --method randinit                                \
    --src-path ${SAVEDIR}/dcfs_det_${NET}_base${SPLIT_ID}/model_final.pth                    \
    --save-dir ${SAVEDIR}/dcfs_det_${NET}_base${SPLIT_ID}
BASE_WEIGHT=${SAVEDIR}/dcfs_det_${NET}_base${SPLIT_ID}/model_reset_surgery.pth

 ------------------------------ Novel Fine-tuning ------------------------------- 
--> 2. TFA-like, i.e. run seed0~9 10 times for gFSOD on voc
classloss="DC" # "CE"

for seed in 0 1 2 3 4 5 6 7 8 9

第二次fine-tune使用的预训练权重应该是第一次fine-tune结果目录下的权重？

**Comment by gaobb** [comment]
非常感谢指出该问题。你是对的，应该使用base model weight。

之所以出现这个问题，是当时训练完我再次评测，代码发布时忘记删掉当前模型的权重了。现在已删除并更新。
