### ISSUE TITLE
关于dcloss中的fs_class

### ISSUE THREAD

**Issue by WeiX998** [gaobb/DCFS#7]
作者你好, 请问这里的x['fs_class']是如何得到的,我无法找到相应的代码
<img width="892" alt="image" src="https://github.com/gaobb/DCFS/assets/64784379/0ace36da-9391-4578-9dab-0f7de93a9b2c">

**Comment by gaobb** [comment]
hi,  非常感谢您对我们工作的关注。

x['fs_class'] 只在模型训练阶段用到，其是few-shot 标注给定的。具体请在下列链接中查看：
https://github.com/gaobb/DCFS/blob/36bcc991f08cb5c088eb5c7d42b65bd7573067f0/dcfs/dataloader/dataset_mapper.py#L163

**Comment by WeiX998** [comment]
感谢您的解答!
